theme: jekyll-theme-midnight
title: A Princely library
description: An unsorted collection of odds and ends, mostly excerpts from articles related to Prince. Intended as a back-up where I can easily retrieve such information when I need it.